#!/usr/bin/env bash

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE_DEFAULT="${PROJECT_DIR}/configs/default.env"

die() {
  echo "Error: $*" >&2
  exit 1
}

require_apple_silicon_mac() {
  [[ "$(uname -s)" == "Darwin" ]] || die "This project supports macOS only."
  [[ "$(uname -m)" == "arm64" ]] || die "This project supports Apple Silicon (arm64) only."

  local major
  major=$(sw_vers -productVersion | cut -d. -f1)
  [[ "${major}" =~ ^[0-9]+$ ]] || die "Unable to detect the macOS version."
  (( major >= 26 )) || die "Apple container requires macOS 26 or newer."
}

require_container_cli() {
  command -v container >/dev/null 2>&1 || die "Apple container is not installed. Run: ./install-container.sh"
}

require_container_system() {
  container system status >/dev/null 2>&1 || die "Apple container services are not running. Run: container system start"
}

load_config() {
  local config_file="${1:-${CONFIG_FILE_DEFAULT}}"
  [[ -f "${config_file}" ]] || die "Configuration not found: ${config_file}. Run ./configure.sh first."
  # This is a project-local shell configuration file generated by configure.sh.
  # shellcheck source=/dev/null
  source "${config_file}"

  : "${CONTAINER_NAME:?Missing CONTAINER_NAME}"
  : "${IMAGE_NAME:?Missing IMAGE_NAME}"
  : "${CONFIG_VOLUME:?Missing CONFIG_VOLUME}"
  : "${RESOLUTION:?Missing RESOLUTION}"
  : "${DPI:?Missing DPI}"
  : "${STREAM_SCALE:?Missing STREAM_SCALE}"
  : "${FRAMERATE:?Missing FRAMERATE}"
  : "${TIMEZONE:?Missing TIMEZONE}"
  : "${HTTP_PORT:?Missing HTTP_PORT}"
  : "${HTTPS_PORT:?Missing HTTPS_PORT}"
  : "${CPUS:?Missing CPUS}"
  : "${MEMORY:?Missing MEMORY}"
  : "${BUILD_CPUS:?Missing BUILD_CPUS}"
  : "${BUILD_MEMORY:?Missing BUILD_MEMORY}"
  : "${SHM_SIZE:?Missing SHM_SIZE}"

  # Use the current English default for configuration files without a language setting.
  UBUNTU_VERSION=${UBUNTU_VERSION:-24.04}
  BASE_IMAGE=${BASE_IMAGE:-ghcr.io/tatsuyai713/webtop-kde-base-arm64-u${UBUNTU_VERSION}:1.1.0}
  [[ "${UBUNTU_VERSION}" == "22.04" || "${UBUNTU_VERSION}" == "24.04" ]] || die "UBUNTU_VERSION must be 22.04 or 24.04."
  USER_LANGUAGE=${USER_LANGUAGE:-en}
  [[ "${USER_LANGUAGE}" == "en" || "${USER_LANGUAGE}" == "ja" ]] || die "USER_LANGUAGE must be en or ja."
  KEYBOARD_LAYOUT=${KEYBOARD_LAYOUT:-us}
  [[ "${KEYBOARD_LAYOUT}" == "us" || "${KEYBOARD_LAYOUT}" == "jp" ]] || die "KEYBOARD_LAYOUT must be us or jp."
  INSTALL_ROS2=${INSTALL_ROS2:-true}
  INSTALL_DEV_TOOLS=${INSTALL_DEV_TOOLS:-true}
  ENABLE_XRDP=${ENABLE_XRDP:-true}
  RDP_PORT=${RDP_PORT:-3389}
  FOXGLOVE_PORT=${FOXGLOVE_PORT:-8765}
  ROSBRIDGE_PORT=${ROSBRIDGE_PORT:-9090}
  [[ "${INSTALL_ROS2}" == "true" || "${INSTALL_ROS2}" == "false" ]] || die "INSTALL_ROS2 must be true or false."
  [[ "${INSTALL_DEV_TOOLS}" == "true" || "${INSTALL_DEV_TOOLS}" == "false" ]] || die "INSTALL_DEV_TOOLS must be true or false."
  [[ "${ENABLE_XRDP}" == "true" || "${ENABLE_XRDP}" == "false" ]] || die "ENABLE_XRDP must be true or false."
  MOUNT_HOME=${MOUNT_HOME:-true}
  MOUNT_SSH=${MOUNT_SSH:-true}
  SSL_DIR=${SSL_DIR:-}
}

ensure_config() {
  local config_file="${1:-${CONFIG_FILE_DEFAULT}}"
  [[ -f "${config_file}" ]] && return 0

  [[ -t 0 ]] || die "Configuration not found: ${config_file}. Run ./configure.sh --config ${config_file} first."
  echo "No configuration found at: ${config_file}"
  echo "Running the container configuration wizard before continuing..."
  "${PROJECT_DIR}/configure.sh" --config "${config_file}"
}

container_exists() {
  container inspect "$1" >/dev/null 2>&1
}

image_exists() {
  container image inspect "$1" >/dev/null 2>&1
}

volume_exists() {
  container volume inspect "$1" >/dev/null 2>&1
}

calculate_scale() {
  awk -v dpi="$1" 'BEGIN { printf "%.2f", dpi / 96 }'
}

detect_host_timezone() {
  local timezone_path timezone
  timezone_path=$(readlink /etc/localtime 2>/dev/null || true)
  if [[ "${timezone_path}" == *"/zoneinfo/"* ]]; then
    timezone=${timezone_path#*"/zoneinfo/"}
    [[ -n "${timezone}" ]] && { printf '%s\n' "${timezone}"; return 0; }
  fi

  if [[ -r /etc/timezone ]]; then
    IFS= read -r timezone < /etc/timezone || true
    [[ -n "${timezone}" ]] && { printf '%s\n' "${timezone}"; return 0; }
  fi

  printf '%s\n' UTC
}
